dataset: "fmri"

train:
  epochs: 2000
  batch_size: 128
  lr: 1.0e-3
  seq_len: 24

score_network:
  res_layers: 3
  channels: 128
  nheads: 6
  num_steps: 800
  diffusion_embedding_dim: 128
  freq_tier: 2
  seq_len: 24
  lma_affine: True
  revin_affine: True
  t_enc_att: 'full'
  s_enc_att: 'full'
  enc_att_mask: True
  season_att: 'full'
  season_att_mask: True
  corr_att: 'full'
  corr_att_mask: True
  
diff_model:
  is_conditional: False
  beta_start: 0.0001
  beta_end: 0.5
  schedule: 'linear'
  sample_size: 256
  sample_steps: 800
  

